route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications

receivers:
  - name: email-notifications
    email_configs:
      - to: myemail89@gmail.com  #use that email where you want to recieve notifications
        from: test@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: myemail@gmail.com
        auth_identity: myemail@gmail.com
        auth_password: bdmq omqh vvkk zoqx  # ⚠️ Use App Password here
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
